### ISSUE TITLE
LineChart Android example?

### ISSUE THREAD

**Issue by m1ga** [adrienblot/SimplyCharts#1]
Just found your module on gittio and I'm very excited to see a crossplatform graph framework!
Do you have an example on how to setup the data object for a LineChart on Android?

**Comment by adrienblot** [comment]
Hi!
Sorry I started this project last week, so it's far from finishing. This module uses those charting libraries:
https://github.com/PhilJay/MPAndroidChart
https://github.com/danielgindi/Charts
If you're interested MPAndroidChart has a wiki explaining the API. I will try to keep the same API.
If you want to create a LineChart:

```
    //Create Window
    var window = $.UI.create('Window');

     //Create chart view
    var module = require('nz.co.simplypayroll.charts');
    var chart = module.createLineChartView({ 
        backgroundColor: "#E5EFCE",  
        descriptionFont: {
            fontFamily: 'Graphik-Light',
            fontSize: 10
        },
        noDataTextDescription: 'plip',
        drawGridBackground: true,
        gridBackgroundColor: 'white',
        drawBorders: true,
        borderColor: "#74AD50",
        borderWidth: 2,
        maxVisibleValueCount: 2
    });

    window.add(chart);          
    Alloy.Globals.navMenu.open(window);

    //Change legend properties
    var legend = chart.getLegend();
    legend.setPosition('ABOVE_CHART_LEFT');

    //Create data
    var lineData = module.createLineData({
        xVals: ['x1', 'x2', 'x3'], 
        data: {
            'line1': [{xIndex: 0, val: 10 }, {xIndex: 1, val: 20 }, {xIndex: 3, val: 30 }]
        }
    });
    chart.setData(lineData);

    //Change XAxis properties
    var xAxis = chart.getXAxis();
    xAxis.setPosition('BOTTOM');
    xAxis.setTextColor("#74AD50");
```

The way the data object is created will probably change to be compliant with the charting library. I needed something fast in order to test the views.

Hope this helps.

**Comment by m1ga** [comment]
Thank you the example! Helps a lot
